### ISSUE TITLE
OpenAI Whisper API compatability

### ISSUE THREAD

**Issue by raivisdejus** [ahmetoner/whisper-asr-webservice#227] opened 2024-06-22 12:30 UTC
Compatibility with [OpenAI whisper API](https://platform.openai.com/docs/api-reference/audio) would make this solution great drop-in replacement for different use cases.

**Comment by debjit** [comment] 2024-06-23 05:55
+1

**Comment by krausality** [comment] 2024-07-19 21:41
+1

**Comment by ayancey** [comment] 2024-08-10 15:57
Dupe of #182

**Closed by ayancey** 2024-08-10 15:57 UTC
