### ISSUE TITLE
exec /opt/poetry-venv/bin/poetry: exec format error

### ISSUE THREAD

**Issue by avsavani** [ahmetoner/whisper-asr-webservice#34] opened 2022-11-06 20:57 UTC
While running CPU Dockerfile on AWS ECS Fargate, getting this poetry exec format error.  The Fargate task definition stays in the Pending state and  I cannot change it to the running state. Any idea why?

**Comment by ahmetoner** [comment] 2022-11-06 21:22
Hi @avsavani 

It seems the issue is related with the build architecture. I checked previous GitHub action built image and they are on linux/amd64. What is your Fargate cluster architecture? Is it linux/arm64? If yes, the next release will support multi arch with docker buildx.

Greetings,
Ahmet

**Comment by gautampambhar** [comment] 2022-11-07 13:48
Hi, I am in the same boat and running it on a Fargate linux. Any idea when is the next release?  Thank you!

**Comment by ahmetoner** [comment] 2022-11-07 13:52
Hi @gautampambhar,

I plan to create a new version by tomorrow at the latest.

Greetings,
Ahmet

**Comment by gautampambhar** [comment] 2022-11-08 15:36
Hi Just checking in to see if the AWS fargate deployment issue got resolved with the previous release. I am still getting the same error on AWS fargate logs.

**Comment by ahmetoner** [comment] 2022-11-09 20:35
Hi @gautampambhar,

I am still implementing the multi architecture version. Sorry for being late. I will let you know when it is ready. 

Greetings,
Ahmet

**Closed** 2022-11-16 22:33 UTC
